_target_: src.models.liqe_module.LIQEModule

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 1e-5
  weight_decay: 1e-4

scheduler:
  _target_: cosine_annealing_warmup.CosineAnnealingWarmupRestarts
  _partial_: true
  first_cycle_steps: 6e+3
  cycle_mult: 1.0
  max_lr: 1e-5
  min_lr: 1e-8
  warmup_steps: 1e+3
  gamma: 0.95

net:
  _target_: src.models.components.liqe_mos.liqe
  device: "cuda"

# compile model for faster training with pytorch 2.0
compile: false
