_target_: src.models.maniqa_module.ManiqaModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 1e-5
  weight_decay: 1e-5

scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  _partial_: true
  T_max: 50
  eta_min: 0

net:
  _target_: MANIQA.models.maniqa.MANIQA
  embed_dim: 768
  num_outputs: 1
  dim_mlp: 768
  patch_size: 8
  img_size: 224
  window_size: 4
  depths: [2,2]
  num_heads: [4,4]
  num_tab: 2
  scale: 0.8


# compile model for faster training with pytorch 2.0
compile: false
